name: Deploy to EC2 via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH and deploy
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ec2-13-53-193-165.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/id_rsa ubuntu@ec2-13-53-193-165.eu-north-1.compute.amazonaws.com << 'EOF'
            cd ~/ai-blog-writer
            git pull origin main
            npm install
            npm run build
            pm2 describe ai-blog > /dev/null && pm2 restart ai-blog || pm2 start "npx serve -s dist" --name ai-blog
            pm2 save
          EOF
